Update tonic to 0.11 using a version range
TrueLayer/ginepro pull request #50
Opened 2024-02-27 10:34 UTC by kplattret

There is a new version of `tonic` available. This updates the various `Cargo.toml` files to accept a range of versions for that crate, allowing to update as needed.

2024-02-27 11:38 UTC, eopb commented on shared_proto/Cargo.toml
The versions in this file don't need range versions because they are not published

2024-02-27 11:38 UTC, eopb commented on tests/Cargo.toml
The same applies for these versions

2024-02-27 11:39 UTC, eopb requested changes
Looks good. Just a couple of places it could be a little simpler

2024-02-27 13:22 UTC, eopb approved these changes

2024-02-27 13:22 UTC, merged

2024-03-01 00:40 UTC, njhill commented
Thank you @eopb @kplattret!